App_search:
    resource: 'routing/Users/UserSearch/UserSearch.yml'
App_size:
    resource: 'routing/Users/UserSize/UserSize.yml'
App_delivery:
    resource: 'routing/Users/UserDelivery/UserDelivery.yml'
App_create_delivery:
    resource: 'routing/Users/UserDelivery/CreateUserDelivery.yml'
App_delete_delivery:
    resource: 'routing/Users/UserDelivery/DeleteUserDelivery.yml'
App_set_userSize:
    resource: 'routing/Users/UserSize/SetUserSize.yml'
