App_search:
    resource: 'routing/Users/UserSearch/UserSearch.yml'
App_size:
    resource: 'routing/Users/UserSize/UserSize.yml'
App_delivery:
    resource: 'routing/Users/UserDelivery/UserDelivery.yml'
App_create_delivery:
    resource: 'routing/Users/UserDelivery/CreateUserDelivery.yml'
App_delete_delivery:
    resource: 'routing/Users/UserDelivery/DeleteUserDelivery.yml'
delete_userDelivery:
    path: '/set/userSize/{userSize_id}/{size}'
    controller: App\Infrastructure\Controller\User\UserSize\SetUserSizeController::setUserSize